@startuml
interface Iterable<T>

interface Collection<E> extends Iterable

abstract class AbstractCollection<E> implements Collection

interface Queue<E> extends Collection{

    boolean add(E e); //抛异常
    boolean offer(E e);
    E remove();//抛异常
    E poll();
    E element();//抛异常
    E peek();
}

interface Deque<E> extends Queue

interface BlockingQueue<E> extends Queue

interface BlockingDeque<E> extends BlockingQueue, Deque

class LinkedBlockingDeque<E> extends AbstractQueue implements BlockingDeque

abstract class AbstractQueue<E> extends AbstractCollection implements Queue


interface Comparable<T>{
}
interface Delayed extends Comparable{
}

class DelayQueue<E extends Delayed> extends AbstractQueue implements BlockingQueue{
}
@enduml