@startuml
interface IGamePlayer{
    login(String user, String psd);
    killBoss();
    upgrade();

    IGamePlayer getProxy();
}

class GamePlayerProxy implements IGamePlayer{
    IGamePlayer _gamePlayer;
}

class ReallyGamePlayer implements IGamePlayer{
    GamePlayerProxy myProxy;
}
GamePlayerProxy o--o ReallyGamePlayer:互相持有
@enduml